@ECHO OFF
SETLOCAL
PUSHD "%~dp0"

SET THREAD_COUNT=10
REM
SET BATCH_READ_SIZE=1
REM SET LIMIT_ROW_COUNT=0
SET LIMIT_ROW_COUNT=50

FOR /L %%I IN (1, 1, %THREAD_COUNT%) DO START FromSqlServerToBlobs.DEV.cmd %BATCH_READ_SIZE% %LIMIT_ROW_COUNT%

ENDLOCAL
